/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entity.*;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class CRUD extends javax.swing.JFrame {

    String idPegawai;
    
    public CRUD(String idPegawai) throws SQLException {
        initComponents();
        this.idPegawai = idPegawai;
        Mobil.readMobil();
        Truk.readTruk();
        Kendaraan.readKendaraan();
        setTableContent();
        TableMobil.getTableHeader().setReorderingAllowed(false);
        CreateTableTruk.getTableHeader().setReorderingAllowed(false);
    }
    
    private void setTableContent(){
        if (ChooseVehicle.getSelectedItem().equals("CAR")) {
            DefaultTableModel modelMobil = (DefaultTableModel) TableMobil.getModel();
            modelMobil.setRowCount(0);
            try {
                jPanel1.removeAll();
                jPanel1.repaint();
                jPanel1.revalidate();
                
                jPanel1.add(menuMobil);
                jPanel1.repaint();
                jPanel1.revalidate();
                ArrayList<Mobil> dataMobil = Mobil.readMobil();
                for (Mobil mobil : dataMobil) {
                    String id = mobil.getId_Kendaraan();
                    String mesin = mobil.getUkuranmesin_Kendaraan();
                    String model = mobil.getModel();
                    String warna = mobil.getWarna();
                    String idPegawai = mobil.getIdPegawai();
                    String jumlahPenumpang = String.valueOf(mobil.getJumlah_penumpang());
                    String jumlahPintu = String.valueOf(mobil.getJumlah_pintu());
                    String[] row = {id,mesin,model,warna,jumlahPintu,jumlahPenumpang,idPegawai};
                    modelMobil.addRow(row);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                DefaultTableModel modeltruk = (DefaultTableModel) CreateTableTruk.getModel();
                modeltruk.setRowCount(0);
                jPanel1.removeAll();
                jPanel1.repaint();
                jPanel1.revalidate();
                
                jPanel1.add(menuTruk);
                jPanel1.repaint();
                jPanel1.revalidate();
                ArrayList<Truk> dataMobil = Truk.readTruk();
                for (Truk truk : dataMobil) {
                    String id = truk.getId_Kendaraan();
                    String mesin = truk.getUkuranmesin_Kendaraan();
                    String model = truk.getModel();
                    String warna = truk.getWarna();
                    String idPegawai = truk.getIdPegawai();
                    String jenisBak = truk.getJenis_bak();
                    String kapasitas = truk.getKapasitas_maksimum();
                    String[] row = {id,mesin,model,warna,jenisBak,kapasitas,idPegawai};
                    modeltruk.addRow(row);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelButton = new javax.swing.JPanel();
        ChooseVehicle = new javax.swing.JComboBox<>();
        CreateButtonVehicle = new javax.swing.JButton();
        UpdateButtonVehicle = new javax.swing.JButton();
        BackButtonVehicle = new javax.swing.JButton();
        DeleteButtonVehicle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        menuTruk = new javax.swing.JPanel();
        CreateTruk = new javax.swing.JPanel();
        CreateIDKendaraan = new javax.swing.JTextField();
        CreateModel = new javax.swing.JComboBox<>();
        CreateUkuranMesin = new javax.swing.JComboBox<>();
        CreateWarna = new javax.swing.JComboBox<>();
        CreateKapasitasBak = new javax.swing.JComboBox<>();
        CreateJenisBak = new javax.swing.JComboBox<>();
        CreateTabelScroll = new javax.swing.JScrollPane();
        CreateTableTruk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuMobil = new javax.swing.JPanel();
        CreateMobil = new javax.swing.JPanel();
        IDMobil = new javax.swing.JTextField();
        ModelMobil = new javax.swing.JComboBox<>();
        UkuranMesinMobil = new javax.swing.JComboBox<>();
        WarnaMobil = new javax.swing.JComboBox<>();
        PenumpangMobil = new javax.swing.JComboBox<>();
        JumlahPintu = new javax.swing.JComboBox<>();
        TabelMobil = new javax.swing.JScrollPane();
        TableMobil = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        MainPanel.setBackground(new java.awt.Color(204, 255, 204));
        MainPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        MainPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        MainPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelButton.setBackground(new java.awt.Color(51, 51, 51));
        PanelButton.setPreferredSize(new java.awt.Dimension(800, 90));

        ChooseVehicle.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        ChooseVehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRUCK", "CAR" }));
        ChooseVehicle.setPreferredSize(new java.awt.Dimension(72, 23));
        ChooseVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseVehicleActionPerformed(evt);
            }
        });

        CreateButtonVehicle.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        CreateButtonVehicle.setText("CREATE");
        CreateButtonVehicle.setPreferredSize(new java.awt.Dimension(80, 30));
        CreateButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonVehicleActionPerformed(evt);
            }
        });

        UpdateButtonVehicle.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        UpdateButtonVehicle.setText("UPDATE");
        UpdateButtonVehicle.setPreferredSize(new java.awt.Dimension(80, 30));
        UpdateButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonVehicleActionPerformed(evt);
            }
        });

        BackButtonVehicle.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        BackButtonVehicle.setText("BACK");
        BackButtonVehicle.setPreferredSize(new java.awt.Dimension(80, 30));
        BackButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonVehicleActionPerformed(evt);
            }
        });

        DeleteButtonVehicle.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        DeleteButtonVehicle.setText("DELETE");
        DeleteButtonVehicle.setPreferredSize(new java.awt.Dimension(80, 30));
        DeleteButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonVehicleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonLayout = new javax.swing.GroupLayout(PanelButton);
        PanelButton.setLayout(PanelButtonLayout);
        PanelButtonLayout.setHorizontalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ChooseVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeleteButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(BackButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelButtonLayout.setVerticalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CreateButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ChooseVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UpdateButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DeleteButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BackButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        MainPanel.add(PanelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        jPanel1.setLayout(new java.awt.CardLayout());

        menuTruk.setMaximumSize(new java.awt.Dimension(800, 500));
        menuTruk.setLayout(new java.awt.CardLayout());

        CreateTruk.setBackground(new java.awt.Color(255, 255, 255));
        CreateTruk.setMaximumSize(new java.awt.Dimension(800, 500));
        CreateTruk.setMinimumSize(new java.awt.Dimension(800, 500));
        CreateTruk.setPreferredSize(new java.awt.Dimension(800, 500));
        CreateTruk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateIDKendaraan.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CreateIDKendaraan.setPreferredSize(new java.awt.Dimension(180, 55));
        CreateIDKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateIDKendaraanActionPerformed(evt);
            }
        });
        CreateTruk.add(CreateIDKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, -1));

        CreateModel.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CreateModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light", "Medium", "Heavy" }));
        CreateModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateModelActionPerformed(evt);
            }
        });
        CreateTruk.add(CreateModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, 61));

        CreateUkuranMesin.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CreateUkuranMesin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4500 CC", "5500 CC", "7500 CC" }));
        CreateTruk.add(CreateUkuranMesin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 220, 55));

        CreateWarna.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CreateWarna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yellow", "Green", "Orange" }));
        CreateWarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateWarnaActionPerformed(evt);
            }
        });
        CreateTruk.add(CreateWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 220, 61));

        CreateKapasitasBak.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CreateKapasitasBak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 TONS", "8 TONS", "15 TONS" }));
        CreateKapasitasBak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateKapasitasBakActionPerformed(evt);
            }
        });
        CreateTruk.add(CreateKapasitasBak, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 220, 61));

        CreateJenisBak.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CreateJenisBak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FLAT", "BOX" }));
        CreateJenisBak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateJenisBakActionPerformed(evt);
            }
        });
        CreateTruk.add(CreateJenisBak, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 220, 57));

        CreateTabelScroll.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CreateTabelScroll.setMaximumSize(new java.awt.Dimension(450, 90));
        CreateTabelScroll.setMinimumSize(new java.awt.Dimension(450, 90));
        CreateTabelScroll.setPreferredSize(new java.awt.Dimension(450, 90));

        CreateTableTruk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateTableTruk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "Model", "Engine Type", "Color", "Bed Type", "Bed Capacity", "Employee ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CreateTableTruk.setMaximumSize(new java.awt.Dimension(450, 90));
        CreateTableTruk.setMinimumSize(new java.awt.Dimension(450, 90));
        CreateTableTruk.setPreferredSize(new java.awt.Dimension(450, 90));
        CreateTableTruk.getTableHeader().setReorderingAllowed(false);
        CreateTableTruk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateTableTrukMouseClicked(evt);
            }
        });
        CreateTabelScroll.setViewportView(CreateTableTruk);

        CreateTruk.add(CreateTabelScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 740, 120));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel1.setText("Bed Capacity");
        CreateTruk.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 220, 30));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel2.setText("VEHICLE ID");
        CreateTruk.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, 30));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setText("Engine Type");
        CreateTruk.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 220, 30));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel4.setText("Bed Type");
        CreateTruk.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 220, 30));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setText("Model");
        CreateTruk.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, 30));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel6.setText("Color");
        CreateTruk.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 220, 30));

        menuTruk.add(CreateTruk, "card2");

        jPanel1.add(menuTruk, "card3");

        menuMobil.setMaximumSize(new java.awt.Dimension(800, 500));
        menuMobil.setLayout(new java.awt.CardLayout());

        CreateMobil.setBackground(new java.awt.Color(255, 255, 255));
        CreateMobil.setMaximumSize(new java.awt.Dimension(800, 500));
        CreateMobil.setMinimumSize(new java.awt.Dimension(800, 500));
        CreateMobil.setPreferredSize(new java.awt.Dimension(800, 500));
        CreateMobil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IDMobil.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        IDMobil.setPreferredSize(new java.awt.Dimension(180, 55));
        IDMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDMobilActionPerformed(evt);
            }
        });
        CreateMobil.add(IDMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 220, -1));

        ModelMobil.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        ModelMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEDAN", "MPV", "SUV" }));
        ModelMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelMobilActionPerformed(evt);
            }
        });
        CreateMobil.add(ModelMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, 61));

        UkuranMesinMobil.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        UkuranMesinMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1500 CC", "1500 CC TURBO", "2000 CC", "2500 CC TURBO", "3000 CC" }));
        UkuranMesinMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UkuranMesinMobilActionPerformed(evt);
            }
        });
        CreateMobil.add(UkuranMesinMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 220, 55));

        WarnaMobil.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        WarnaMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "WHITE", "BLACK", "RED", "YELLOW", "BLUE", "GRAY", "SILVER" }));
        WarnaMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarnaMobilActionPerformed(evt);
            }
        });
        CreateMobil.add(WarnaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 220, 61));

        PenumpangMobil.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        PenumpangMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "7" }));
        CreateMobil.add(PenumpangMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 220, 61));

        JumlahPintu.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        JumlahPintu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4" }));
        CreateMobil.add(JumlahPintu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 220, 57));

        TabelMobil.setMaximumSize(new java.awt.Dimension(450, 90));
        TabelMobil.setMinimumSize(new java.awt.Dimension(450, 90));
        TabelMobil.setPreferredSize(new java.awt.Dimension(450, 90));

        TableMobil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle ID", "Model", "Engine", "Color", "Doors", "Passenger", "Employee ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableMobil.setDoubleBuffered(true);
        TableMobil.setMaximumSize(new java.awt.Dimension(450, 90));
        TableMobil.setMinimumSize(new java.awt.Dimension(450, 90));
        TableMobil.setPreferredSize(new java.awt.Dimension(450, 90));
        TableMobil.getTableHeader().setReorderingAllowed(false);
        TableMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMobilMouseClicked(evt);
            }
        });
        TabelMobil.setViewportView(TableMobil);

        CreateMobil.add(TabelMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 740, 120));

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel7.setText("Model");
        CreateMobil.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 220, 30));

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel8.setText("Engine");
        CreateMobil.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 220, 30));

        jLabel9.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel9.setText("Doors");
        CreateMobil.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 220, 30));

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel10.setText("Color");
        CreateMobil.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 220, 30));

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel11.setText("Passenger");
        CreateMobil.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 220, 30));

        jLabel12.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel12.setText("VEHICLE ID");
        CreateMobil.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, 30));

        menuMobil.add(CreateMobil, "card2");

        jPanel1.add(menuMobil, "card3");

        MainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonVehicleActionPerformed
        LocalDate tanggal = LocalDate.now();
        String format = tanggal.format(DateTimeFormatter.ISO_DATE);

        if (ChooseVehicle.getSelectedItem().equals("CAR")) {
            try {
                String idMobil = IDMobil.getText();
                String model = (String) ModelMobil.getSelectedItem();
                String warna = (String) WarnaMobil.getSelectedItem();
                String mesin = (String) UkuranMesinMobil.getSelectedItem();
                String pintu = (String) JumlahPintu.getSelectedItem();
                String penumpang = (String) PenumpangMobil.getSelectedItem();

                // Validasi data kosong
                if (idMobil.isEmpty() || model == null || warna == null || mesin == null || pintu == null || penumpang == null) {
                    JOptionPane.showMessageDialog(null, "Please fill the Vehicle ID first!");
                    return; // Berhenti jika ada data yang kosong
                }

                Kendaraan.createKendaraan(idMobil, mesin, model, warna, this.idPegawai);
                Mobil.createMobil(penumpang, pintu, idMobil, mesin, model, warna, idPegawai);
                Dokumen.createKendaraan(null, "Car", format);
                ChooseVehicleActionPerformed(evt);
                JOptionPane.showMessageDialog(null, "Car added successfully.");
            } catch (SQLException ex) {
                Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                String idTruk = CreateIDKendaraan.getText();
                String model = (String) CreateModel.getSelectedItem();
                String warna = (String) CreateWarna.getSelectedItem();
                String mesin = (String) CreateUkuranMesin.getSelectedItem();
                String jenisBak = (String) CreateJenisBak.getSelectedItem();
                String kapasitasBak = (String) CreateKapasitasBak.getSelectedItem();

                // Validasi data kosong
                if (idTruk.isEmpty() || model == null || warna == null || mesin == null || jenisBak == null || kapasitasBak == null) {
                    JOptionPane.showMessageDialog(null, "Please fill the Vehicle ID first!");
                    return; // Berhenti jika ada data yang kosong
                }

                Kendaraan.createKendaraan(idTruk, mesin, model, warna, this.idPegawai);
                Truk.createTruk(jenisBak, kapasitasBak, idTruk, kapasitasBak, model, warna, idPegawai);
                Dokumen.createKendaraan(null, "Truck", format);
                ChooseVehicleActionPerformed(evt);
                JOptionPane.showMessageDialog(null, "Truck added successfully.");
            } catch (SQLException ex) {
                Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_CreateButtonVehicleActionPerformed

    private void BackButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonVehicleActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_BackButtonVehicleActionPerformed

    private void UpdateButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonVehicleActionPerformed
        int selectedrow = CreateTableTruk.getSelectedRow();
        int selectedrow1 = TableMobil.getSelectedRow();

        if (selectedrow == -1 && selectedrow1 == -1) {
            JOptionPane.showMessageDialog(null, "Choose first, which vehicle you want to delete!");
        } else {
            if (ChooseVehicle.getSelectedItem().equals("CAR")) {
                try {
                    String idMobil = IDMobil.getText();
                    String model = (String) ModelMobil.getSelectedItem();
                    String warna = (String) WarnaMobil.getSelectedItem();
                    String mesin = (String) UkuranMesinMobil.getSelectedItem();
                    String pintu = (String) JumlahPintu.getSelectedItem();
                    String penumpang = (String) PenumpangMobil.getSelectedItem();

                    if (idMobil.isEmpty() || model == null || warna == null || mesin == null || pintu == null || penumpang == null) {
                        JOptionPane.showMessageDialog(null, "Please fill the Vehicle ID first!");
                        return;
                    }

                    Mobil.updateMobil(pintu, penumpang, idMobil);
                    Kendaraan.updateKendaraan(idMobil, mesin, model, warna, idPegawai);
                    ChooseVehicleActionPerformed(evt);
                    JOptionPane.showMessageDialog(null, "Car updated successfully.");
                } catch (SQLException ex) {
                    Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    String idTruk = CreateIDKendaraan.getText();
                    String model = (String) CreateModel.getSelectedItem();
                    String warna = (String) CreateWarna.getSelectedItem();
                    String mesin = (String) CreateUkuranMesin.getSelectedItem();
                    String jenisBak = (String) CreateJenisBak.getSelectedItem();
                    String kapasitasBak = (String) CreateKapasitasBak.getSelectedItem();

                    if (idTruk.isEmpty() || model == null || warna == null || mesin == null || jenisBak == null || kapasitasBak == null) {
                        JOptionPane.showMessageDialog(null, "Please fill the Vehicle ID first!");
                        return;
                    }

                    Truk.updateTruk(jenisBak, kapasitasBak, idTruk);
                    Kendaraan.updateKendaraan(idTruk, mesin, model, warna, idPegawai);
                    ChooseVehicleActionPerformed(evt);
                    JOptionPane.showMessageDialog(null, "Truck updated successfully.");
                } catch (SQLException ex) {
                    Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } 
    }//GEN-LAST:event_UpdateButtonVehicleActionPerformed

    private void DeleteButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonVehicleActionPerformed
        if (ChooseVehicle.getSelectedItem().equals("CAR")) {
            try {
                Mobil.deleteMobil(IDMobil.getText());
                Kendaraan.deleteKendaraan(IDMobil.getText());
                ChooseVehicleActionPerformed(evt);
                JOptionPane.showMessageDialog(null, "Car deleted successfully.");
            } catch (SQLException ex) {
                Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try {
                Truk.deleteTruk(CreateIDKendaraan.getText());
                Kendaraan.deleteKendaraan(CreateIDKendaraan.getText());
                ChooseVehicleActionPerformed(evt);
                JOptionPane.showMessageDialog(null, "Truck deleted successfully.");
            } catch (SQLException ex) {
                Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_DeleteButtonVehicleActionPerformed

    private void ModelMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelMobilActionPerformed

    private void UkuranMesinMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UkuranMesinMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UkuranMesinMobilActionPerformed

    private void WarnaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarnaMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WarnaMobilActionPerformed

    private void ChooseVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseVehicleActionPerformed
        setTableContent();
    }//GEN-LAST:event_ChooseVehicleActionPerformed

    private void CreateTableTrukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateTableTrukMouseClicked
        int selectrow = CreateTableTruk.getSelectedRow();
        Object id = CreateTableTruk.getValueAt(selectrow, 0);
        CreateIDKendaraan.setText((String) id);
        
        
    }//GEN-LAST:event_CreateTableTrukMouseClicked

    private void TableMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMobilMouseClicked
        int selectedRow = TableMobil.getSelectedRow();
        Object id = TableMobil.getValueAt(selectedRow, 0);
        IDMobil.setText((String) id);
    }//GEN-LAST:event_TableMobilMouseClicked

    private void IDMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDMobilActionPerformed

    private void CreateIDKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateIDKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateIDKendaraanActionPerformed

    private void CreateJenisBakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateJenisBakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateJenisBakActionPerformed

    private void CreateModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateModelActionPerformed

    private void CreateWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateWarnaActionPerformed

    private void CreateKapasitasBakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateKapasitasBakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateKapasitasBakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CRUD(null).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(CRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButtonVehicle;
    private javax.swing.JComboBox<String> ChooseVehicle;
    private javax.swing.JButton CreateButtonVehicle;
    private javax.swing.JTextField CreateIDKendaraan;
    private javax.swing.JComboBox<String> CreateJenisBak;
    private javax.swing.JComboBox<String> CreateKapasitasBak;
    private javax.swing.JPanel CreateMobil;
    private javax.swing.JComboBox<String> CreateModel;
    private javax.swing.JScrollPane CreateTabelScroll;
    private javax.swing.JTable CreateTableTruk;
    private javax.swing.JPanel CreateTruk;
    private javax.swing.JComboBox<String> CreateUkuranMesin;
    private javax.swing.JComboBox<String> CreateWarna;
    private javax.swing.JButton DeleteButtonVehicle;
    private javax.swing.JTextField IDMobil;
    private javax.swing.JComboBox<String> JumlahPintu;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JComboBox<String> ModelMobil;
    private javax.swing.JPanel PanelButton;
    private javax.swing.JComboBox<String> PenumpangMobil;
    private javax.swing.JScrollPane TabelMobil;
    private javax.swing.JTable TableMobil;
    private javax.swing.JComboBox<String> UkuranMesinMobil;
    private javax.swing.JButton UpdateButtonVehicle;
    private javax.swing.JComboBox<String> WarnaMobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menuMobil;
    private javax.swing.JPanel menuTruk;
    // End of variables declaration//GEN-END:variables
}
