/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Entity.Mobil;
import Entity.Truk;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ManajerForm extends javax.swing.JFrame {

    /**
     * Creates new form ManajerForm
     */
    public ManajerForm() throws SQLException {
        initComponents();
        setTableTruk();
        setTableMobil();
        TableMobil.getTableHeader().setReorderingAllowed(false);
        CreateTableTruk1.getTableHeader().setReorderingAllowed(false);
    }
    
    private void setTableMobil() throws SQLException{
        DefaultTableModel modelMobil = (DefaultTableModel) TableMobil.getModel();
        modelMobil.setRowCount(0);
        ArrayList<Mobil> dataMobil = Mobil.readMobil();
        for (Mobil mobil : dataMobil) {
            String id = mobil.getId_Kendaraan();
            String mesin = mobil.getUkuranmesin_Kendaraan();
            String model = mobil.getModel();
            String warna = mobil.getWarna();
            String idPegawai = mobil.getIdPegawai();
            String jumlahPenumpang = String.valueOf(mobil.getJumlah_penumpang());
            String jumlahPintu = String.valueOf(mobil.getJumlah_pintu());
            String[] row = {id,mesin,model,warna,jumlahPintu,jumlahPenumpang,idPegawai};
            modelMobil.addRow(row);
        }
    }
    
    private void setTableTruk() throws SQLException{
        DefaultTableModel modeltruk = (DefaultTableModel) CreateTableTruk1.getModel();
        modeltruk.setRowCount(0);
        ArrayList<Truk> dataMobil = Truk.readTruk();
        for (Truk truk : dataMobil) {
            String id = truk.getId_Kendaraan();
            String mesin = truk.getUkuranmesin_Kendaraan();
            String model = truk.getModel();
            String warna = truk.getWarna();
            String idPegawai = truk.getIdPegawai();
            String jenisBak = truk.getJenis_bak();
            String kapasitas = truk.getKapasitas_maksimum();
            String[] row = {id,mesin,model,warna,jenisBak,kapasitas,idPegawai};
            modeltruk.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateTabelScroll = new javax.swing.JScrollPane();
        CreateTableTruk = new javax.swing.JTable();
        TabelMobil = new javax.swing.JScrollPane();
        TableMobil = new javax.swing.JTable();
        CreateTabelScroll1 = new javax.swing.JScrollPane();
        CreateTableTruk1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDok = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        CreateTableTruk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateTableTruk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ENGINE", "MODEL", "COLOR", "BED TYPE", "BED CAPACITY", "DOKUMEN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CreateTableTruk.setPreferredSize(new java.awt.Dimension(450, 90));
        CreateTabelScroll.setViewportView(CreateTableTruk);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableMobil.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        TableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Car ID", "Engine", "Model", "Color", "Doors", "Passenger", "Document"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableMobil.setMaximumSize(new java.awt.Dimension(750, 50));
        TableMobil.setMinimumSize(new java.awt.Dimension(750, 50));
        TableMobil.setPreferredSize(new java.awt.Dimension(750, 50));
        TableMobil.getTableHeader().setReorderingAllowed(false);
        TabelMobil.setViewportView(TableMobil);

        getContentPane().add(TabelMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 741, 160));

        CreateTableTruk1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        CreateTableTruk1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Truck ID", "Engine", "Model", "Color", "Bed Type", "Bed Capacity", "Document"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CreateTableTruk1.setMaximumSize(new java.awt.Dimension(750, 50));
        CreateTableTruk1.setMinimumSize(new java.awt.Dimension(750, 50));
        CreateTableTruk1.setPreferredSize(new java.awt.Dimension(750, 50));
        CreateTableTruk1.getTableHeader().setReorderingAllowed(false);
        CreateTabelScroll1.setViewportView(CreateTableTruk1);

        getContentPane().add(CreateTabelScroll1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 741, 152));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setText("Cars");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 30));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel2.setText("Truck");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 30));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnDok.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnDok.setText("DOCUMENT");
        btnDok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addComponent(btnDok)
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDok, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
        login.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokActionPerformed
        try {
            DokumenGUI dokumenGUI = new DokumenGUI();
            dokumenGUI.setVisible(true);
            dokumenGUI.pack();
            dokumenGUI.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(ManajerForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManajerForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ManajerForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane CreateTabelScroll;
    private javax.swing.JScrollPane CreateTabelScroll1;
    private javax.swing.JTable CreateTableTruk;
    private javax.swing.JTable CreateTableTruk1;
    private javax.swing.JScrollPane TabelMobil;
    private javax.swing.JTable TableMobil;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
